### PR TITLE
Fix ESLint configuration

### LINKED ISSUE #38: [Feature] Add support for GitHub Actions for CI
### Description

Currently, the repo is set up to use Travis, but we deprecated Travis a while back.

- [ ] Set up GitHub Actions
- [ ] Remove Travis configuration

### Designs

_No response_

### PR DESCRIPTION
**Pull request by hdavidethan**
# Description

When we first started this project, we used Babel to assist in using the cleaner ESM syntax. Now that this syntax is natively supported by Node.js, I removed Babel completely and replaced it with Node's import system. I also set up lint checking with GitHub Actions and removed Travis since that is no longer being used.

The scraper code is now in the new scraper repo and removed from this repository.

Closes #38 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

This PR should include the new lint check on GitHub Actions. This check passes. Additionally, you can test the linter locally using `npm run lint`.

**Test Configuration**:

- Node.js version: 16
- OS: Mac OS Monterey

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/models/fceEntry.js [hunk 1]
```diff
@@ -82,36 +82,36 @@ export class FCEEntry {
...
-        case "responseRate":
-        case "hrsPerWeek":
-          this[label] = this._castToNum(data[labelCount]);
-          break;
-        default:
-          if (label.includes("rating")) {
-            this.rating.push(this._castToNum(data[labelCount]));
-          }
-          break;
+      case "semester":
```
Comment (btwj) [inline src/models/fceEntry.js:85]: I suspect this file belongs with the scraper instead, but you can keep it here for now. I will move it over soon.

**Review by btwj — APPROVED** [review]
LGTM
